### ISSUE TITLE
SSL errors, cannot log into Nexus and download via Manager

### ISSUE THREAD

**Issue by caerendil** [TanninOne/modorganizer#531]
I've recently built an new PC.  I copied Mod Organizer and its subdirectories from old PC into the new one.  Everything is functioning correctly, I can kick off Skyrim (SKSE), LOOT, Creation Kit etc without any issues, except I am getting SSL errors and cannot automatically log in to Nexus and use the Download with Manger option.

I've tried putting the most recent OpenSSL DDLs in the MO root directory with the EXE.
Other versions of those DLLs do exist on the PC but they are all in the programs folders but in the Windows system directories like WOW64.

I tried archiving my old MO and doing a fresh install.  Still didn't work.  Same issue.

MO version is 1.3.11
I use Firefox (ver 44.0)
I can log into Nexus and download manually
I don't believe there are any Registry settings for MO are there?

Sample MO start-up log attached.

I'm now at a bit of a loss to know what steps to take next.  Thanks

[Mod Organizer Startup Log.txt](https://github.com/TanninOne/modorganizer/files/112147/Mod.Organizer.Startup.Log.txt)

**Comment by caerendil** [comment]
That should have read 
Other versions of those DLLs do exist on the PC but they are all in the programs folders NOT in the Windows system directories like WOW64

**Comment by Leer0x** [comment]
What is your Nexus version in the workarounds part of the Mod Organizer settings?
Try setting it to 0.61.9 and make sure the version goes in correctly.

**Comment by caerendil** [comment]
Sorry, forgot to put that on the original post
It is 0.61.9

I just removed it and put it in again to be sure...and it connected!

Very odd so I've just done some more testing, and I wonder if somehow I had
a space character as well as the zero in the first part.
I put in zero-space and it fails to connect, as you would expect.
I put in zero and then move on to the next section and it is fine.

Somewhat embarrassing!

Many thanks for your help (I should have tried that myself in the first
place and not assumed it was correct just to look at) and for such an
essential product.  Looking forward to using it for Fallout 4 once I get
modding with that later this year.

Graham.

**Comment by Leer0x** [comment]
It's completely fine @caerendil I fixed this myself a while back and found most Nexus errors have to do with the Nexus version and the Nexus site recognizing MO AS a mod manager.

**Comment by caerendil** [comment]
Yes, it's something I've had to update myself in the past in order to keep
it logging in so I visually checked it this time and it looked fine.  I
didn't go the whole hog and type it in again to make sure.
Lessons learned!

**Comment by TanninOne** [comment]
seems to be solved then

**Comment by caerendil** [comment]
Yes, many thanks Tannin one.

**Comment by caerendil** [comment]
Hi TanninOne
Sorry, it isn't working still.  Hope I can bug you for some tips on tracing
why?
I'm trying to work out what might be the cause.  On occasion it seems to be
OK, like Thursday where I downloaded some mods from the Nexus.
Prior to that, since our last email exchange it wasn't working and the last
couple of days it won't connect either, I still get the QSslSocket errors.
Very odd!

I've tried thinking of what software may have been running, or not, on
Thursday for it to work but I can't think thgat I did, or didn't, do
anything different.

Mod Organiser is working perfectly on my son's PC, which I've also just
built from the remnants of my old one.

Cheers

Graham
